### ISSUE TITLE
Provide a "wavy" arrow as a macro?

### ISSUE THREAD

**Issue by vendethiel** [natefaubion/sparkler#15]
Something like `~>` ? That'd be like `function { }`:

```
doSomething(~> {
  String ...
})
```

**Comment by yuchi** [comment]
probably this

``` js
macro ~> {
  rule {} => { function }
}
```

could do the job.

**Comment by natefaubion** [comment]
@yuchi yes, the macro itself is really simple. The problem is macro modules can't import other macro modules currently, so you'd have to put that in any file that wants to use it. You might be able to do it manually using the low level API for loading macro sources. There's an ongoing [PR](https://github.com/mozilla/sweet.js/pull/378) for ES6 module support in sweet.js that solves this problem.
