### ISSUE TITLE
Incorrect match compilation

### ISSUE THREAD

**Issue by swannodette** [natefaubion/sparkler#2]
```
function maranget {
  case (*,     false, true ) => 1
  case (false, true,  *    ) => 2
  case (*,     *,     false) => 3
  case (*,     *,     true ) => 4
}
console.log(maranget(false,true,false));
```

generates

``` js
function maranget$704(a0$705, a1$706, a2$707) {
    if (a1$706 === false && a2$707 === true) {
        return 1;
    }
    if (a2$707 === false) {
        return 3;
    }
    if (a2$707 === true) {
        return 4;
    }
    if (a0$705 === false && a1$706 === true) {
        return 2;
    }
    throw new TypeError('No match');
}
console.log(maranget$704(false, true, false));
```

However this is not correct, the function call will emit 3 instead of 2 - order of the matches specified by the user is not preserved.

**Comment by natefaubion** [comment]
Nice catch. This can be fixed by a tweak to the grafting algorithm. Instead of starting at the beginning of the list in the inner loop and checking for identical patterns, it should check in reverse from the current `i` and stop once it find one that doesn't match. That way it only grafts ones that are clustered together.
